### ISSUE TITLE
Find 2 more developers

### ISSUE THREAD

**Issue by rmc3408** [iPlayed-games/backend#2]
Invited Daniel to Join on IPlayed

**Comment by rmc3408** [comment]
@DLittlefield81 , My friend was invited to join to our group Daniel:

Daniel's TimeTable:
- Monday - Full Time
- Tuesday - Full Time
- Wednesday - Morning
- Thrusday - Morning

**Comment by rmc3408** [comment]
Talking with Friend Elvin Hatamov 
https://www.linkedin.com/in/elvinhatamov/

**Comment by mihirchauhan29** [comment]
Hello @DLittlefield81 @rmc3408 
I'm new to open source contribution and i found that you are currently working on this reservation system project. I'm backend developer with experience in nodejs, express js, mongodb and jest so I found my self good fit for this project because it's in initial stage and i would like to join this team to contribute so let me know how can I join this group.

**Comment by rmc3408** [comment]
> Hello @DLittlefield81 @rmc3408 I'm new to open source contribution and i found that you are currently working on this reservation system project. I'm backend developer with experience in nodejs, express js, mongodb and jest so I found my self good fit for this project because it's in initial stage and i would like to join this team to contribute so let me know how can I join this group.

Hello @mihirchauhan29, Could you send us a resume and any project that you have done it ?

**Comment by mihirchauhan29** [comment]
Sure , i will share my resume on @rmc3408 mail id.
